version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./project/.env
    environment:
      MYSQL_ROOT_PASSWORD: abc12345
      MYSQL_DATABASE: 4linux_db
    ports:
      - 3307:3306
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  project:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./project/.env
    ports:
      - 3003:3003
    image: node-mysql-app
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    volumes:
      - ./project:/project

volumes:
  db-config:
  db-data: